// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ProyectoTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() throws MalformedURLException {
    driver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), DesiredCapabilities.firefox());
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void proyecto() {
    // Test name: Proyecto
    // Step # | name | target | value | comment
    // 1 | click | linkText=Inicio |  | 
    driver.findElement(By.linkText("Inicio")).click();
    // 2 | click | linkText=Productos |  | 
    driver.findElement(By.linkText("Productos")).click();
    // 3 | click | linkText=Nosotros |  | 
    driver.findElement(By.linkText("Nosotros")).click();
    // 4 | click | linkText=Contacto |  | 
    driver.findElement(By.linkText("Contacto")).click();
    // 5 | click | css=.copyright |  | 
    driver.findElement(By.cssSelector(".copyright")).click();
    // 6 | click | css=.footer-links |  | 
    driver.findElement(By.cssSelector(".footer-links")).click();
    // 7 | open | /index |  | 
    driver.get("https://tienda-ecommers.onrender.com/index");
    // 8 | setWindowSize | 977x899 |  | 
    driver.manage().window().setSize(new Dimension(977, 899));
    // 9 | click | linkText=Iniciar sesión |  | 
    driver.findElement(By.linkText("Iniciar sesión")).click();
    // 10 | click | linkText=¿Registrarte? |  | 
    driver.findElement(By.linkText("¿Registrarte?")).click();
    // 11 | click | id=username |  | 
    driver.findElement(By.id("username")).click();
    // 12 | click | id=username |  | 
    driver.findElement(By.id("username")).click();
    // 13 | click | id=username |  | 
    driver.findElement(By.id("username")).click();
    // 14 | type | id=username | Rocha | 
    driver.findElement(By.id("username")).sendKeys("Rocha");
    // 15 | click | id=email |  | 
    driver.findElement(By.id("email")).click();
    // 16 | type | id=email | anysalazaraj@gmail.com | 
    driver.findElement(By.id("email")).sendKeys("anysalazaraj@gmail.com");
    // 17 | click | id=password |  | 
    driver.findElement(By.id("password")).click();
    // 18 | type | id=password | 123456789 | 
    driver.findElement(By.id("password")).sendKeys("123456789");
    // 19 | click | css=button |  | 
    driver.findElement(By.cssSelector("button")).click();
    // 20 | click | id=email |  | 
    driver.findElement(By.id("email")).click();
    // 21 | type | id=email | anysalazaraj@gmail.com | 
    driver.findElement(By.id("email")).sendKeys("anysalazaraj@gmail.com");
    // 22 | click | id=password |  | 
    driver.findElement(By.id("password")).click();
    // 23 | type | id=password | 123456789 | 
    driver.findElement(By.id("password")).sendKeys("123456789");
    // 24 | click | css=button |  | 
    driver.findElement(By.cssSelector("button")).click();
    // 25 | click | css=button > strong |  | 
    driver.findElement(By.cssSelector("button > strong")).click();
    // 26 | click | css=#cart-btn > span |  | 
    driver.findElement(By.cssSelector("#cart-btn > span")).click();
    // 27 | click | css=.close-cart |  | 
    driver.findElement(By.cssSelector(".close-cart")).click();
    // 28 | click | css=.product-card:nth-child(1) .add-to-cart |  | 
    driver.findElement(By.cssSelector(".product-card:nth-child(1) .add-to-cart")).click();
    // 29 | click | css=#cart-btn > span |  | 
    driver.findElement(By.cssSelector("#cart-btn > span")).click();
    // 30 | click | css=.remove-item |  | 
    driver.findElement(By.cssSelector(".remove-item")).click();
    // 31 | click | css=.close-cart |  | 
    driver.findElement(By.cssSelector(".close-cart")).click();
    // 32 | click | css=.product-card:nth-child(1) .add-to-cart |  | 
    driver.findElement(By.cssSelector(".product-card:nth-child(1) .add-to-cart")).click();
    // 33 | mouseOver | css=.product-card:nth-child(1) .add-to-cart |  | 
    {
      WebElement element = driver.findElement(By.cssSelector(".product-card:nth-child(1) .add-to-cart"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 34 | mouseOut | css=.product-card:nth-child(1) .add-to-cart |  | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 35 | click | css=.product-card:nth-child(2) .add-to-cart |  | 
    driver.findElement(By.cssSelector(".product-card:nth-child(2) .add-to-cart")).click();
    // 36 | click | css=.product-card:nth-child(3) .add-to-cart |  | 
    driver.findElement(By.cssSelector(".product-card:nth-child(3) .add-to-cart")).click();
    // 37 | mouseOver | css=.product-card:nth-child(3) .add-to-cart |  | 
    {
      WebElement element = driver.findElement(By.cssSelector(".product-card:nth-child(3) .add-to-cart"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 38 | mouseOut | css=.product-card:nth-child(3) .add-to-cart |  | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 39 | click | css=.product-card:nth-child(4) .add-to-cart |  | 
    driver.findElement(By.cssSelector(".product-card:nth-child(4) .add-to-cart")).click();
    // 40 | mouseOver | css=.product-card:nth-child(4) .add-to-cart |  | 
    {
      WebElement element = driver.findElement(By.cssSelector(".product-card:nth-child(4) .add-to-cart"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 41 | mouseOut | css=.product-card:nth-child(4) .add-to-cart |  | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 42 | click | css=#cart-btn > span |  | 
    driver.findElement(By.cssSelector("#cart-btn > span")).click();
    // 43 | click | css=.checkout-btn |  | 
    driver.findElement(By.cssSelector(".checkout-btn")).click();
    // 44 | click | css=.close-cart |  | 
    driver.findElement(By.cssSelector(".close-cart")).click();
    // 45 | click | css=.product-card:nth-child(10) .add-to-cart |  | 
    driver.findElement(By.cssSelector(".product-card:nth-child(10) .add-to-cart")).click();
    // 46 | mouseOver | css=.product-card:nth-child(10) .add-to-cart |  | 
    {
      WebElement element = driver.findElement(By.cssSelector(".product-card:nth-child(10) .add-to-cart"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 47 | mouseOut | css=.product-card:nth-child(10) .add-to-cart |  | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 48 | click | css=#cart-btn > span |  | 
    driver.findElement(By.cssSelector("#cart-btn > span")).click();
    // 49 | click | css=.remove-item |  | 
    driver.findElement(By.cssSelector(".remove-item")).click();
    // 50 | click | css=.close-cart |  | 
    driver.findElement(By.cssSelector(".close-cart")).click();
    // 51 | click | css=p > button:nth-child(2) |  | 
    driver.findElement(By.cssSelector("p > button:nth-child(2)")).click();
  }
}
